version: '2'
services:
    db:
        image: silintl/mariadb:latest
        ports:
            - "3306"
        environment:
            MYSQL_ROOT_PASSWORD: r00tp@ss!
            MYSQL_HOST: db
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass

    broker:
        image: silintl/idp-id-broker:latest
        ports:
            - "8080:80"
        depends_on:
            - db
        volumes:
          - ./run-broker.sh:/data/run-broker.sh
        working_dir: /data
        environment:
            EMAIL_SERVICE_accessToken: fake
            EMAIL_SERVICE_assertValidIp: "false"
            EMAIL_SERVICE_baseUrl: fake
            EMAIL_SERVICE_validIpRanges: 10.0.0.0/128
            IDP_NAME: idp1
            MYSQL_HOST: db
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: dummy-root-password
            API_ACCESS_KEYS: abc123
            HELP_CENTER_URL: https://example.com/#/help
            PASSWORD_FORGOT_URL: https://example.com/#/forgot
            PASSWORD_PROFILE_URL: https://example.com/#/profile
            SUPPORT_EMAIL: support@example.com
            EMAIL_SIGNATURE: Dummy Signature for Tests
        command: whenavail db 3306 60 ./run-broker.sh

    test:
        image: silintl/php7:latest
        volumes:
          - .:/data
        depends_on:
            - db
            - broker
        working_dir: /data
        command: whenavail db 3306 60 ./run-tests.sh

